# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T07:33:10+00:00



import argparse
import json
import os
from typing import *
from typing import Optional, Union

from autogen.mcp.mcp_proxy import MCPProxy
from autogen.mcp.mcp_proxy.security import APIKeyHeader, BaseSecurity
from fastapi import Query
from starlette.requests import Request

from models import (
    APIError,
    BadWordFilterResponse,
    BINLookupResponse,
    BrowserBotResponse,
    ConvertResponse,
    EmailValidateResponse,
    EmailVerifyResponse,
    GeocodeAddressResponse,
    GeocodeReverseResponse,
    HLRLookupResponse,
    HostReputationResponse,
    IPBlocklistResponse,
    IPInfoResponse,
    IPProbeResponse,
    PhonePlaybackResponse,
    PhoneValidateResponse,
    PhoneVerifyResponse,
    SMSVerifyResponse,
    UALookupResponse,
    URLInfoResponse,
    VerifySecurityCodeResponse,
)

app = MCPProxy(
    contact={
        'email': 'ops@neutrinoapi.com',
        'name': 'Neutrino API',
        'url': 'https://www.neutrinoapi.com/',
    },
    description='The general-purpose API',
    title='Neutrino API',
    version='3.6.3',
    servers=[{'url': 'https://neutrinoapi.net'}],
)


@app.post(
    '/bad-word-filter',
    description=""" Detect bad words, swear words and profanity in a given text """,
    tags=['content_filtering'],
    security=[
        APIKeyHeader(name="api-key"),
        APIKeyHeader(name="user-id"),
    ],
)
def bad_word_filter(request: Request):
    """
    Bad Word Filter
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/bin-list-download',
    description=""" Download our entire BIN database for direct use on your own systems """,
    tags=['bin_lookup_management'],
    security=[
        APIKeyHeader(name="api-key"),
        APIKeyHeader(name="user-id"),
    ],
)
def b_i_n_list_download(
    include_iso3: Optional[bool] = Query(False, alias='include-iso3'),
    include_8digit: Optional[bool] = Query(False, alias='include-8digit'),
):
    """
    BIN List Download
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/bin-lookup',
    description=""" Perform a BIN (Bank Identification Number) or IIN (Issuer Identification Number) lookup """,
    tags=['bin_lookup_management', 'ip_address_management'],
    security=[
        APIKeyHeader(name="api-key"),
        APIKeyHeader(name="user-id"),
    ],
)
def b_i_n_lookup(
    bin_number: str = Query(..., alias='bin-number'),
    customer_ip: Optional[str] = Query(None, alias='customer-ip'),
):
    """
    BIN Lookup
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/browser-bot',
    description=""" Browser bot can extract content, interact with keyboard and mouse events, and execute JavaScript on a website """,
    tags=['user_agent_information', 'url_inspection_services'],
    security=[
        APIKeyHeader(name="api-key"),
        APIKeyHeader(name="user-id"),
    ],
)
def browser_bot(request: Request):
    """
    Browser Bot
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/convert',
    description=""" A currency and unit conversion tool """,
    tags=['data_validation_services'],
    security=[
        APIKeyHeader(name="api-key"),
        APIKeyHeader(name="user-id"),
    ],
)
def convert(
    from_value: str = Query(..., alias='from-value'),
    from_type: str = Query(..., alias='from-type'),
    to_type: str = Query(..., alias='to-type'),
):
    """
    Convert
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/email-validate',
    description=""" Parse, validate and clean an email address """,
    tags=['data_validation_services'],
    security=[
        APIKeyHeader(name="api-key"),
        APIKeyHeader(name="user-id"),
    ],
)
def email_validate(
    email: str, fix_typos: Optional[bool] = Query(False, alias='fix-typos')
):
    """
    Email Validate
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/email-verify',
    description=""" SMTP based email address verification """,
    tags=['data_validation_services'],
    security=[
        APIKeyHeader(name="api-key"),
        APIKeyHeader(name="user-id"),
    ],
)
def email_verify(
    email: str, fix_typos: Optional[bool] = Query(False, alias='fix-typos')
):
    """
    Email Verify
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/geocode-address',
    description=""" Geocode an address, partial address or just the name of a place """,
    tags=['address_geocoding'],
    security=[
        APIKeyHeader(name="api-key"),
        APIKeyHeader(name="user-id"),
    ],
)
def geocode_address(
    address: Optional[str] = None,
    house_number: Optional[str] = Query(None, alias='house-number'),
    street: Optional[str] = None,
    city: Optional[str] = None,
    county: Optional[str] = None,
    state: Optional[str] = None,
    postal_code: Optional[str] = Query(None, alias='postal-code'),
    country_code: Optional[str] = Query(None, alias='country-code'),
    language_code: Optional[str] = Query('en', alias='language-code'),
    fuzzy_search: Optional[bool] = Query(False, alias='fuzzy-search'),
):
    """
    Geocode Address
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/geocode-reverse',
    description=""" Convert a geographic coordinate (latitude and longitude) into a real world address """,
    tags=['address_geocoding'],
    security=[
        APIKeyHeader(name="api-key"),
        APIKeyHeader(name="user-id"),
    ],
)
def geocode_reverse(
    latitude: str,
    longitude: str = ...,
    language_code: Optional[str] = Query('en', alias='language-code'),
    zoom: Optional[str] = 'address',
):
    """
    Geocode Reverse
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/hlr-lookup',
    description=""" Connect to the global mobile cellular network and retrieve the status of a mobile device """,
    tags=['data_validation_services'],
    security=[
        APIKeyHeader(name="api-key"),
        APIKeyHeader(name="user-id"),
    ],
)
def h_l_r_lookup(
    number: str, country_code: Optional[str] = Query(None, alias='country-code')
):
    """
    HLR Lookup
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/host-reputation',
    description=""" Check the reputation of an IP address, domain name or URL against a comprehensive list of blacklists and blocklists """,
    tags=['ip_address_management', 'security_code_verification'],
    security=[
        APIKeyHeader(name="api-key"),
        APIKeyHeader(name="user-id"),
    ],
)
def host_reputation(
    host: str,
    list_rating: Optional[int] = Query(3, alias='list-rating'),
    zones: Optional[str] = None,
):
    """
    Host Reputation
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/html-clean',
    description=""" Clean and sanitize untrusted HTML """,
    tags=['html_content_manipulation'],
    security=[
        APIKeyHeader(name="api-key"),
        APIKeyHeader(name="user-id"),
    ],
)
def h_t_m_l_clean(request: Request):
    """
    HTML Clean
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/html-render',
    description=""" Render HTML content to PDF, JPG or PNG """,
    tags=['html_content_manipulation'],
    security=[
        APIKeyHeader(name="api-key"),
        APIKeyHeader(name="user-id"),
    ],
)
def h_t_m_l_render(request: Request):
    """
    HTML Render
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/image-resize',
    description=""" Resize an image and output as either JPEG or PNG """,
    tags=['image_processing_tools'],
    security=[
        APIKeyHeader(name="api-key"),
        APIKeyHeader(name="user-id"),
    ],
)
def image_resize(request: Request):
    """
    Image Resize
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/image-watermark',
    description=""" Watermark one image with another image """,
    tags=['image_processing_tools'],
    security=[
        APIKeyHeader(name="api-key"),
        APIKeyHeader(name="user-id"),
    ],
)
def image_watermark(request: Request):
    """
    Image Watermark
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/ip-blocklist',
    description=""" The IP Blocklist API will detect potentially malicious or dangerous IP addresses """,
    tags=['ip_address_management'],
    security=[
        APIKeyHeader(name="api-key"),
        APIKeyHeader(name="user-id"),
    ],
)
def i_p_blocklist(
    ip: str, vpn_lookup: Optional[bool] = Query(False, alias='vpn-lookup')
):
    """
    IP Blocklist
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/ip-blocklist-download',
    description=""" This API is a direct feed to our IP blocklist data """,
    tags=['ip_address_management'],
    security=[
        APIKeyHeader(name="api-key"),
        APIKeyHeader(name="user-id"),
    ],
)
def i_p_blocklist_download(
    format: Optional[str] = 'csv',
    include_vpn: Optional[bool] = Query(False, alias='include-vpn'),
    cidr: Optional[bool] = False,
    ip6: Optional[bool] = False,
):
    """
    IP Blocklist Download
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/ip-info',
    description=""" Get location information about an IP address and do reverse DNS (PTR) lookups """,
    tags=['ip_address_management'],
    security=[
        APIKeyHeader(name="api-key"),
        APIKeyHeader(name="user-id"),
    ],
)
def i_p_info(
    ip: str, reverse_lookup: Optional[bool] = Query(False, alias='reverse-lookup')
):
    """
    IP Info
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/ip-probe',
    description=""" Execute a realtime network probe against an IPv4 or IPv6 address """,
    tags=['ip_address_management'],
    security=[
        APIKeyHeader(name="api-key"),
        APIKeyHeader(name="user-id"),
    ],
)
def i_p_probe(ip: str):
    """
    IP Probe
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/phone-playback',
    description=""" Make an automated call to any valid phone number and playback an audio message """,
    tags=['data_validation_services', 'security_code_verification'],
    security=[
        APIKeyHeader(name="api-key"),
        APIKeyHeader(name="user-id"),
    ],
)
def phone_playback(request: Request):
    """
    Phone Playback
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/phone-validate',
    description=""" Parse, validate and get location information about a phone number """,
    tags=['data_validation_services', 'ip_address_management'],
    security=[
        APIKeyHeader(name="api-key"),
        APIKeyHeader(name="user-id"),
    ],
)
def phone_validate(
    number: str,
    country_code: Optional[str] = Query(None, alias='country-code'),
    ip: Optional[str] = None,
):
    """
    Phone Validate
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/phone-verify',
    description=""" Make an automated call to any valid phone number and playback a unique security code """,
    tags=['data_validation_services', 'security_code_verification'],
    security=[
        APIKeyHeader(name="api-key"),
        APIKeyHeader(name="user-id"),
    ],
)
def phone_verify(request: Request):
    """
    Phone Verify
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/qr-code',
    description=""" Generate a QR code as a PNG image """,
    tags=['qr_code_creator'],
    security=[
        APIKeyHeader(name="api-key"),
        APIKeyHeader(name="user-id"),
    ],
)
def q_r_code(request: Request):
    """
    QR Code
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/sms-verify',
    description=""" Send a unique security code to any mobile device via SMS """,
    tags=['security_code_verification', 'data_validation_services'],
    security=[
        APIKeyHeader(name="api-key"),
        APIKeyHeader(name="user-id"),
    ],
)
def s_m_s_verify(request: Request):
    """
    SMS Verify
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/ua-lookup',
    description=""" Parse, validate and get detailed user-agent information from a user agent string or from client hints """,
    tags=['user_agent_information'],
    security=[
        APIKeyHeader(name="api-key"),
        APIKeyHeader(name="user-id"),
    ],
)
def u_a_lookup(
    ua: str,
    ua_version: Optional[str] = Query(None, alias='ua-version'),
    ua_platform: Optional[str] = Query(None, alias='ua-platform'),
    ua_platform_version: Optional[str] = Query(None, alias='ua-platform-version'),
    ua_mobile: Optional[str] = Query(None, alias='ua-mobile'),
    device_model: Optional[str] = Query(None, alias='device-model'),
    device_brand: Optional[str] = Query(None, alias='device-brand'),
):
    """
    UA Lookup
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/url-info',
    description=""" Parse, analyze and retrieve content from the supplied URL """,
    tags=['url_inspection_services'],
    security=[
        APIKeyHeader(name="api-key"),
        APIKeyHeader(name="user-id"),
    ],
)
def u_r_l_info(
    url: str,
    fetch_content: Optional[bool] = Query(False, alias='fetch-content'),
    ignore_certificate_errors: Optional[bool] = Query(
        False, alias='ignore-certificate-errors'
    ),
    timeout: Optional[int] = 60,
    retry: Optional[int] = 0,
):
    """
    URL Info
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/verify-security-code',
    description=""" Check if a security code sent via SMS Verify or Phone Verify is valid """,
    tags=['security_code_verification'],
    security=[
        APIKeyHeader(name="api-key"),
        APIKeyHeader(name="user-id"),
    ],
)
def verify_security_code(
    security_code: str = Query(..., alias='security-code'),
    limit_by: Optional[str] = Query(None, alias='limit-by'),
):
    """
    Verify Security Code
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="MCP Server")
    parser.add_argument(
        "transport",
        choices=["stdio", "sse", "streamable-http"],
        help="Transport mode (stdio, sse or streamable-http)",
    )
    args = parser.parse_args()

    if "CONFIG_PATH" in os.environ:
        config_path = os.environ["CONFIG_PATH"]
        app.load_configuration(config_path)

    if "CONFIG" in os.environ:
        config = os.environ["CONFIG"]
        app.load_configuration_from_string(config)

    if "SECURITY" in os.environ:
        security_params = BaseSecurity.parse_security_parameters_from_env(
            os.environ,
        )

        app.set_security_params(security_params)

    mcp_settings = json.loads(os.environ.get("MCP_SETTINGS", "{}"))

    app.get_mcp(**mcp_settings).run(transport=args.transport)
