# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T07:33:10+00:00

from __future__ import annotations

from typing import Dict, List, Optional

from pydantic import BaseModel, Field


class APIError(BaseModel):
    apiError: int = Field(
        ...,
        description='API error code. If set and > 0 then an API error has occurred your request could not be completed',
    )
    apiErrorMsg: str = Field(..., description='API error message')


class BINLookupResponse(BaseModel):
    bin_number: str = Field(
        ..., alias='bin-number', description='The BIN or IIN number'
    )
    card_brand: str = Field(
        ..., alias='card-brand', description='The card brand (e.g. Visa or Mastercard)'
    )
    card_category: str = Field(
        ...,
        alias='card-category',
        description='The card category. There are many different card categories the most common card categories are: CLASSIC, BUSINESS, CORPORATE, PLATINUM, PREPAID',
    )
    card_type: str = Field(
        ...,
        alias='card-type',
        description='The card type, will always be one of: DEBIT, CREDIT, CHARGE CARD',
    )
    country: str = Field(..., description='The full country name of the issuer')
    country_code: str = Field(
        ...,
        alias='country-code',
        description='The ISO 2-letter country code of the issuer',
    )
    country_code3: str = Field(
        ...,
        alias='country-code3',
        description='The ISO 3-letter country code of the issuer',
    )
    currency_code: str = Field(
        ...,
        alias='currency-code',
        description='ISO 4217 currency code associated with the country of the issuer',
    )
    ip_blocklisted: bool = Field(
        ...,
        alias='ip-blocklisted',
        description='True if the customers IP is listed on one of our blocklists, see the <a href="http://www.neutrinoapi.com/api/ip-blocklist/">IP Blocklist API</a>',
    )
    ip_blocklists: List[str] = Field(
        ...,
        alias='ip-blocklists',
        description='An array of strings indicating which blocklists this IP is listed on',
    )
    ip_city: str = Field(
        ..., alias='ip-city', description='The city of the customers IP (if detectable)'
    )
    ip_country: str = Field(
        ..., alias='ip-country', description='The country of the customers IP'
    )
    ip_country_code: str = Field(
        ...,
        alias='ip-country-code',
        description='The ISO 2-letter country code of the customers IP',
    )
    ip_country_code3: str = Field(
        ...,
        alias='ip-country-code3',
        description='The ISO 3-letter country code of the customers IP',
    )
    ip_matches_bin: bool = Field(
        ...,
        alias='ip-matches-bin',
        description='True if the customers IP country matches the BIN country',
    )
    ip_region: str = Field(
        ...,
        alias='ip-region',
        description='The region of the customers IP (if detectable)',
    )
    is_commercial: bool = Field(
        ..., alias='is-commercial', description='Is this a commercial/business use card'
    )
    is_prepaid: bool = Field(
        ...,
        alias='is-prepaid',
        description='Is this a prepaid or prepaid reloadable card',
    )
    issuer: str = Field(..., description='The card issuer')
    issuer_phone: str = Field(
        ..., alias='issuer-phone', description='The card issuers phone number'
    )
    issuer_website: str = Field(
        ..., alias='issuer-website', description='The card issuers website'
    )
    valid: bool = Field(..., description='Is this a valid BIN or IIN number')


class BadWordFilterResponse(BaseModel):
    bad_words_list: List[str] = Field(
        ..., alias='bad-words-list', description='An array of the bad words found'
    )
    bad_words_total: int = Field(
        ..., alias='bad-words-total', description='Total number of bad words detected'
    )
    censored_content: str = Field(
        ...,
        alias='censored-content',
        description='The censored content (only set if censor-character has been set)',
    )
    is_bad: bool = Field(
        ..., alias='is-bad', description='Does the text contain bad words'
    )


class Blacklist(BaseModel):
    is_listed: bool = Field(
        ..., alias='is-listed', description='True if the host is currently black-listed'
    )
    list_host: str = Field(
        ..., alias='list-host', description='The hostname of the DNSBL'
    )
    list_name: str = Field(..., alias='list-name', description='The name of the DNSBL')
    list_rating: int = Field(
        ...,
        alias='list-rating',
        description='The list rating [1-3] with 1 being the best rating and 3 the lowest rating',
    )
    response_time: int = Field(
        ...,
        alias='response-time',
        description='The DNSBL server response time in milliseconds',
    )
    return_code: str = Field(
        ...,
        alias='return-code',
        description='The specific return code for this listing (only set if listed)',
    )
    txt_record: str = Field(
        ...,
        alias='txt-record',
        description='The TXT record returned for this listing (only set if listed)',
    )


class BlocklistSensor(BaseModel):
    blocklist: str = Field(
        ..., description='The primary blocklist category this sensor belongs to'
    )
    description: str = Field(
        ...,
        description='Contains details about the sensor source and what type of malicious activity was detected',
    )
    id: int = Field(
        ...,
        description='The sensor ID. This is a permanent and unique ID for each sensor',
    )


class BrowserBotResponse(BaseModel):
    content: str = Field(
        ...,
        description='The complete raw, decompressed and decoded page content. Usually will be either HTML, JSON or XML',
    )
    elements: List[str] = Field(
        ...,
        description='Array containing all the elements matching the supplied selector. <br>Each element object will contain the text content, HTML content and all current element attributes',
    )
    error_message: str = Field(
        ...,
        alias='error-message',
        description="Contains the error message if an error has occurred ('is-error' will be true)",
    )
    exec_results: List[str] = Field(
        ...,
        alias='exec-results',
        description='If you executed any JavaScript this array holds the results as objects',
    )
    http_redirect_url: str = Field(
        ...,
        alias='http-redirect-url',
        description='The redirected URL if the URL responded with an HTTP redirect',
    )
    http_status_code: int = Field(
        ...,
        alias='http-status-code',
        description='The HTTP status code the URL returned',
    )
    http_status_message: str = Field(
        ...,
        alias='http-status-message',
        description='The HTTP status message the URL returned',
    )
    is_error: bool = Field(
        ...,
        alias='is-error',
        description="True if an error has occurred loading the page. Check the 'error-message' field for details",
    )
    is_http_ok: bool = Field(
        ..., alias='is-http-ok', description='True if the HTTP status is OK (200)'
    )
    is_http_redirect: bool = Field(
        ...,
        alias='is-http-redirect',
        description='True if the URL responded with an HTTP redirect',
    )
    is_secure: bool = Field(
        ..., alias='is-secure', description='True if the page is secured using TLS/SSL'
    )
    is_timeout: bool = Field(
        ...,
        alias='is-timeout',
        description="True if a timeout occurred while loading the page. You can set the timeout with the request parameter 'timeout'",
    )
    language_code: str = Field(
        ...,
        alias='language-code',
        description='The ISO 2-letter language code of the page. Extracted from either the HTML document or via HTTP headers',
    )
    load_time: float = Field(
        ...,
        alias='load-time',
        description='The number of seconds taken to load the page (from initial request until DOM ready)',
    )
    mime_type: str = Field(..., alias='mime-type', description='The document MIME type')
    response_headers: Dict[str, str] = Field(
        ...,
        alias='response-headers',
        description='Map containing all the HTTP response headers the URL responded with',
    )
    security_details: Dict[str, str] = Field(
        ...,
        alias='security-details',
        description='Map containing details of the TLS/SSL setup',
    )
    server_ip: str = Field(
        ..., alias='server-ip', description='The HTTP servers IP address'
    )
    title: str = Field(..., description='The document title')
    url: str = Field(..., description='The page URL')


class ConvertResponse(BaseModel):
    from_type: str = Field(
        ..., alias='from-type', description='The type of the value being converted from'
    )
    from_value: str = Field(
        ..., alias='from-value', description='The value being converted from'
    )
    result: str = Field(
        ..., description='The result of the conversion in string format'
    )
    result_float: float = Field(
        ...,
        alias='result-float',
        description='The result of the conversion as a floating-point number',
    )
    to_type: str = Field(
        ..., alias='to-type', description='The type being converted to'
    )
    valid: bool = Field(
        ...,
        description='True if the conversion was successful and produced a valid result',
    )


class EmailValidateResponse(BaseModel):
    domain: str = Field(..., description='The email domain')
    domain_error: bool = Field(
        ...,
        alias='domain-error',
        description='True if this address has a domain error (e.g. no valid mail server records)',
    )
    email: str = Field(
        ...,
        description='The email address. If you have used the fix-typos option then this will be the fixed address',
    )
    is_disposable: bool = Field(
        ...,
        alias='is-disposable',
        description='True if this address is a disposable, temporary or darknet related email address',
    )
    is_freemail: bool = Field(
        ...,
        alias='is-freemail',
        description='True if this address is a free-mail address',
    )
    is_personal: bool = Field(
        ...,
        alias='is-personal',
        description='True if this address belongs to a person. False if this is a role based address, e.g. admin@, help@, office@, etc.',
    )
    provider: str = Field(..., description='The email service provider domain')
    syntax_error: bool = Field(
        ..., alias='syntax-error', description='True if this address has a syntax error'
    )
    typos_fixed: bool = Field(
        ..., alias='typos-fixed', description='True if typos have been fixed'
    )
    valid: bool = Field(..., description='Is this a valid email')


class EmailVerifyResponse(BaseModel):
    domain: str = Field(..., description='The email domain')
    domain_error: bool = Field(
        ...,
        alias='domain-error',
        description='True if this address has a domain error (e.g. no valid mail server records)',
    )
    email: str = Field(
        ...,
        description='The email address. If you have used the fix-typos option then this will be the fixed address',
    )
    is_catch_all: bool = Field(
        ...,
        alias='is-catch-all',
        description='True if this email domain has a catch-all policy (it will accept mail for any username)',
    )
    is_deferred: bool = Field(
        ...,
        alias='is-deferred',
        description='True if the mail server responded with a temporary failure (either a 4xx response code or unresponsive server). You can retry this address later, we recommend waiting at least 15 minutes before retrying',
    )
    is_disposable: bool = Field(
        ...,
        alias='is-disposable',
        description='True if this address is a disposable, temporary or darknet related email address',
    )
    is_freemail: bool = Field(
        ...,
        alias='is-freemail',
        description='True if this address is a free-mail address',
    )
    is_personal: bool = Field(
        ...,
        alias='is-personal',
        description='True if this address is for a person. False if this is a role based address, e.g. admin@, help@, office@, etc.',
    )
    provider: str = Field(..., description='The email service provider domain')
    smtp_response: str = Field(
        ...,
        alias='smtp-response',
        description='The raw SMTP response message received during verification',
    )
    smtp_status: str = Field(
        ...,
        alias='smtp-status',
        description='The SMTP verification status for the address: <br> <ul> <li>ok - SMTP verification was successful, this is a real address that can receive mail</li> <li>invalid - this is not a valid email address (has either a domain or syntax error)</li> <li>absent - this address is not registered with the email service provider</li> <li>unresponsive - the mail server(s) for this address timed-out or refused to open an SMTP connection</li> <li>unknown - sorry, we could not reliably determine the real status of this address (this address may or may not exist)</li> </ul>',
    )
    syntax_error: bool = Field(
        ..., alias='syntax-error', description='True if this address has a syntax error'
    )
    typos_fixed: bool = Field(
        ..., alias='typos-fixed', description='True if typos have been fixed'
    )
    valid: bool = Field(
        ..., description='Is this a valid email address (syntax and domain is valid)'
    )
    verified: bool = Field(
        ...,
        description='True if this address has passed SMTP verification. Check the smtp-status and smtp-response fields for specific verification details',
    )


class HLRLookupResponse(BaseModel):
    country: str = Field(..., description='The phone number country')
    country_code: str = Field(
        ...,
        alias='country-code',
        description='The number location as an ISO 2-letter country code',
    )
    country_code3: str = Field(
        ...,
        alias='country-code3',
        description='The number location as an ISO 3-letter country code',
    )
    currency_code: str = Field(
        ...,
        alias='currency-code',
        description='ISO 4217 currency code associated with the country',
    )
    current_network: str = Field(
        ...,
        alias='current-network',
        description='The currently used network/carrier name',
    )
    hlr_status: str = Field(
        ...,
        alias='hlr-status',
        description='The HLR lookup status, possible values are: <br> <ul> <li>ok - the HLR lookup was successful and the device is connected</li> <li>absent - the number was once registered but the device has been switched off or out of network range for some time</li> <li>unknown - the number is not known by the mobile network</li> <li>invalid - the number is not a valid mobile MSISDN number</li> <li>fixed-line - the number is a registered fixed-line not mobile</li> <li>voip - the number has been detected as a VOIP line</li> <li>failed - the HLR lookup has failed, we could not determine the real status of this number</li> </ul>',
    )
    hlr_valid: bool = Field(
        ...,
        alias='hlr-valid',
        description='Was the HLR lookup successful. If true then this is a working and registered cell-phone or mobile device (SMS and phone calls will be delivered)',
    )
    imsi: str = Field(
        ...,
        description='The mobile IMSI number (International Mobile Subscriber Identity)',
    )
    international_calling_code: str = Field(
        ...,
        alias='international-calling-code',
        description='The international calling code',
    )
    international_number: str = Field(
        ...,
        alias='international-number',
        description='The number represented in full international format',
    )
    is_mobile: bool = Field(
        ...,
        alias='is-mobile',
        description='True if this is a mobile number (only true with 100% certainty, if the number type is unknown this value will be false)',
    )
    is_ported: bool = Field(
        ...,
        alias='is-ported',
        description='Has this number been ported to another network',
    )
    is_roaming: bool = Field(
        ...,
        alias='is-roaming',
        description='Is this number currently roaming from its origin country',
    )
    local_number: str = Field(
        ...,
        alias='local-number',
        description='The number represented in local dialing format',
    )
    location: str = Field(
        ...,
        description='The number location. Could be a city, region or country depending on the type of number',
    )
    mcc: str = Field(..., description='The mobile MCC number (Mobile Country Code)')
    mnc: str = Field(..., description='The mobile MNC number (Mobile Network Code)')
    msc: str = Field(..., description='The mobile MSC number (Mobile Switching Center)')
    msin: str = Field(
        ...,
        description='The mobile MSIN number (Mobile Subscription Identification Number)',
    )
    number_type: str = Field(
        ...,
        alias='number-type',
        description='The number type, possible values are: <br> <ul> <li>mobile</li> <li>fixed-line</li> <li>premium-rate</li> <li>toll-free</li> <li>voip</li> <li>unknown</li> </ul>',
    )
    number_valid: bool = Field(
        ..., alias='number-valid', description='True if this a valid phone number'
    )
    origin_network: str = Field(
        ..., alias='origin-network', description='The origin network/carrier name'
    )
    ported_network: str = Field(
        ...,
        alias='ported-network',
        description='The ported to network/carrier name (only set if the number has been ported)',
    )
    roaming_country_code: str = Field(
        ...,
        alias='roaming-country-code',
        description='If the number is currently roaming, the ISO 2-letter country code of the roaming in country',
    )


class HostReputationResponse(BaseModel):
    host: str = Field(..., description='The IP address or host name')
    is_listed: bool = Field(
        ..., alias='is-listed', description='Is this host blacklisted'
    )
    list_count: int = Field(
        ...,
        alias='list-count',
        description='The number of DNSBLs the host is listed on',
    )
    lists: List[Blacklist] = Field(
        ..., description='Array of objects for each DNSBL checked'
    )


class IPBlocklistResponse(BaseModel):
    blocklists: List[str] = Field(
        ...,
        description='An array of strings indicating which blocklist categories this IP is listed on',
    )
    cidr: str = Field(
        ...,
        description='The CIDR address for this listing (only set if the IP is listed)',
    )
    ip: str = Field(..., description='The IP address')
    is_bot: bool = Field(
        ...,
        alias='is-bot',
        description='IP is hosting a malicious bot or is part of a botnet. This is a broad category which includes brute-force crackers',
    )
    is_dshield: bool = Field(
        ...,
        alias='is-dshield',
        description='IP has been flagged as a significant attack source by DShield (dshield.org)',
    )
    is_exploit_bot: bool = Field(
        ...,
        alias='is-exploit-bot',
        description='IP is hosting an exploit finding bot or is running exploit scanning software',
    )
    is_hijacked: bool = Field(
        ...,
        alias='is-hijacked',
        description='IP is part of a hijacked netblock or a netblock controlled by a criminal organization',
    )
    is_listed: bool = Field(
        ..., alias='is-listed', description='Is this IP on a blocklist'
    )
    is_malware: bool = Field(
        ...,
        alias='is-malware',
        description='IP is involved in distributing or is running malware',
    )
    is_proxy: bool = Field(
        ...,
        alias='is-proxy',
        description='IP has been detected as an anonymous web proxy or anonymous HTTP proxy',
    )
    is_spam_bot: bool = Field(
        ...,
        alias='is-spam-bot',
        description='IP address is hosting a spam bot, comment spamming or any other spamming type software',
    )
    is_spider: bool = Field(
        ...,
        alias='is-spider',
        description='IP is running a hostile web spider / web crawler',
    )
    is_spyware: bool = Field(
        ...,
        alias='is-spyware',
        description='IP is involved in distributing or is running spyware',
    )
    is_tor: bool = Field(
        ...,
        alias='is-tor',
        description='IP is a Tor node or running a Tor related service',
    )
    is_vpn: bool = Field(
        ...,
        alias='is-vpn',
        description="IP belongs to a public VPN provider (only set if the 'vpn-lookup' option is enabled)",
    )
    last_seen: int = Field(
        ...,
        alias='last-seen',
        description='The unix time when this IP was last seen on any blocklist. IPs are automatically removed after 7 days therefor this value will never be older than 7 days',
    )
    list_count: int = Field(
        ...,
        alias='list-count',
        description='The number of blocklists the IP is listed on',
    )
    sensors: List[BlocklistSensor] = Field(
        ...,
        description='An array of objects containing details on which specific sensors detected the IP',
    )


class IPProbeResponse(BaseModel):
    as_age: int = Field(
        ...,
        alias='as-age',
        description='The age of the autonomous system (AS) in number of years since registration',
    )
    as_cidr: str = Field(
        ..., alias='as-cidr', description='The autonomous system (AS) CIDR range'
    )
    as_country_code: str = Field(
        ...,
        alias='as-country-code',
        description='The autonomous system (AS) ISO 2-letter country code',
    )
    as_country_code3: str = Field(
        ...,
        alias='as-country-code3',
        description='The autonomous system (AS) ISO 3-letter country code',
    )
    as_description: str = Field(
        ...,
        alias='as-description',
        description='The autonomous system (AS) description / company name',
    )
    as_domains: List[str] = Field(
        ...,
        alias='as-domains',
        description='Array of all the domains associated with the autonomous system (AS)',
    )
    asn: str = Field(..., description='The autonomous system (AS) number')
    city: str = Field(..., description='Full city name (if detectable)')
    continent_code: str = Field(
        ..., alias='continent-code', description='ISO 2-letter continent code'
    )
    country: str = Field(..., description='Full country name')
    country_code: str = Field(
        ..., alias='country-code', description='ISO 2-letter country code'
    )
    country_code3: str = Field(
        ..., alias='country-code3', description='ISO 3-letter country code'
    )
    currency_code: str = Field(
        ...,
        alias='currency-code',
        description='ISO 4217 currency code associated with the country',
    )
    host_domain: str = Field(
        ..., alias='host-domain', description='The IPs host domain'
    )
    hostname: str = Field(..., description='The IPs full hostname (PTR)')
    ip: str = Field(..., description='The IP address')
    is_bogon: bool = Field(
        ...,
        alias='is-bogon',
        description='True if this is a bogon IP address such as a private network, local network or reserved address',
    )
    is_hosting: bool = Field(
        ...,
        alias='is-hosting',
        description='True if this IP belongs to a hosting company. Note that this can still be true even if the provider type is VPN/proxy, this occurs in the case that the IP is detected as both types',
    )
    is_isp: bool = Field(
        ...,
        alias='is-isp',
        description='True if this IP belongs to an internet service provider. Note that this can still be true even if the provider type is VPN/proxy, this occurs in the case that the IP is detected as both types',
    )
    is_proxy: bool = Field(
        ..., alias='is-proxy', description='True if this IP ia a proxy'
    )
    is_v4_mapped: bool = Field(
        ...,
        alias='is-v4-mapped',
        description='True if this is a <a href="https://en.wikipedia.org/wiki/IPv6#IPv4-mapped_IPv6_addresses">IPv4 mapped IPv6 address</a>',
    )
    is_v6: bool = Field(
        ..., alias='is-v6', description='True if this is a IPv6 address. False if IPv4'
    )
    is_vpn: bool = Field(..., alias='is-vpn', description='True if this IP ia a VPN')
    provider_description: str = Field(
        ...,
        alias='provider-description',
        description='A description of the provider (usually extracted from the providers website)',
    )
    provider_domain: str = Field(
        ..., alias='provider-domain', description='The domain name of the provider'
    )
    provider_type: str = Field(
        ...,
        alias='provider-type',
        description='The detected provider type, possible values are: <br> <ul> <li>isp - IP belongs to an internet service provider. This includes both mobile, home and business internet providers</li> <li>hosting - IP belongs to a hosting company. This includes website hosting, cloud computing platforms and colocation facilities</li> <li>vpn - IP belongs to a VPN provider</li> <li>proxy - IP belongs to a proxy service. This includes HTTP/SOCKS proxies and browser based proxies</li> <li>university - IP belongs to a university/college/campus</li> <li>government - IP belongs to a government department. This includes military facilities</li> <li>commercial - IP belongs to a commercial entity such as a corporate headquarters or company office</li> <li>unknown - could not identify the provider type</li> </ul>',
    )
    provider_website: str = Field(
        ..., alias='provider-website', description='The website URL for the provider'
    )
    region: str = Field(..., description='Full region name (if detectable)')
    region_code: str = Field(
        ..., alias='region-code', description='ISO 3166-2 region code (if detectable)'
    )
    valid: bool = Field(..., description='True if this is a valid IPv4 or IPv6 address')
    vpn_domain: str = Field(
        ...,
        alias='vpn-domain',
        description='The domain of the VPN provider (may be empty if the VPN domain is not detectable)',
    )


class PhonePlaybackResponse(BaseModel):
    calling: bool = Field(..., description='True if the call is being made now')
    number_valid: bool = Field(
        ..., alias='number-valid', description='True if this a valid phone number'
    )


class PhoneValidateResponse(BaseModel):
    country: str = Field(..., description='The phone number country')
    country_code: str = Field(
        ...,
        alias='country-code',
        description='The phone number country as an ISO 2-letter country code',
    )
    country_code3: str = Field(
        ...,
        alias='country-code3',
        description='The phone number country as an ISO 3-letter country code',
    )
    currency_code: str = Field(
        ...,
        alias='currency-code',
        description='ISO 4217 currency code associated with the country',
    )
    international_calling_code: str = Field(
        ...,
        alias='international-calling-code',
        description='The international calling code',
    )
    international_number: str = Field(
        ...,
        alias='international-number',
        description='The number represented in full international format (E.164)',
    )
    is_mobile: bool = Field(
        ...,
        alias='is-mobile',
        description='True if this is a mobile number. If the number type is unknown this value will be false',
    )
    local_number: str = Field(
        ...,
        alias='local-number',
        description='The number represented in local dialing format',
    )
    location: str = Field(
        ...,
        description='The phone number location. Could be the city, region or country depending on the type of number',
    )
    prefix_network: str = Field(
        ...,
        alias='prefix-network',
        description='The network/carrier who owns the prefix (this only works for some countries, use HLR lookup for global network detection)',
    )
    type: str = Field(
        ...,
        description='The number type based on the number prefix. <br>Possible values are: <br> <ul> <li>mobile</li> <li>fixed-line</li> <li>premium-rate</li> <li>toll-free</li> <li>voip</li> <li>unknown (use HLR lookup)</li> </ul>',
    )
    valid: bool = Field(..., description='Is this a valid phone number')


class PhoneVerifyResponse(BaseModel):
    calling: bool = Field(..., description='True if the call is being made now')
    number_valid: bool = Field(
        ..., alias='number-valid', description='True if this a valid phone number'
    )
    security_code: str = Field(
        ...,
        alias='security-code',
        description='The security code generated, you can save this code to perform your own verification or you can use the <a href="https://www.neutrinoapi.com/api/verify-security-code/">Verify Security Code API</a>',
    )


class SMSVerifyResponse(BaseModel):
    number_valid: bool = Field(
        ..., alias='number-valid', description='True if this a valid phone number'
    )
    security_code: str = Field(
        ...,
        alias='security-code',
        description='The security code generated, you can save this code to perform your own verification or you can use the <a href="https://www.neutrinoapi.com/api/verify-security-code/">Verify Security Code API</a>',
    )
    sent: bool = Field(..., description='True if the SMS has been sent')


class Timezone(BaseModel):
    abbr: str = Field(..., description='The time zone abbreviation', examples=['EDT'])
    date: str = Field(
        ...,
        description="The current date at the time zone (ISO 8601 format 'YYYY-MM-DD')",
        examples=['2021-01-01'],
    )
    id: str = Field(
        ...,
        description='The time zone ID as per the IANA time zone database (tzdata)',
        examples=['America/New_York'],
    )
    name: str = Field(
        ..., description='The full time zone name', examples=['Eastern Daylight Time']
    )
    offset: str = Field(
        ..., description="The UTC offset for the time zone (ISO 8601 format '±hh:mm')"
    )
    time: str = Field(
        ...,
        description="The current time at the time zone (ISO 8601 format 'hh:mm:ss.sss')",
        examples=['12:30:00.00'],
    )


class UALookupResponse(BaseModel):
    browser_engine: str = Field(
        ...,
        alias='browser-engine',
        description='If the client is a web browser which underlying browser engine does it use',
    )
    browser_release: str = Field(
        ...,
        alias='browser-release',
        description='If the client is a web browser which year was this browser version released',
    )
    device_brand: str = Field(
        ..., alias='device-brand', description='The device brand / manufacturer'
    )
    device_height_px: float = Field(
        ...,
        alias='device-height-px',
        description="The device display height in CSS 'px'",
    )
    device_model: str = Field(..., alias='device-model', description='The device model')
    device_model_code: str = Field(
        ..., alias='device-model-code', description='The device model code'
    )
    device_pixel_ratio: float = Field(
        ...,
        alias='device-pixel-ratio',
        description='The device display pixel ratio (the ratio of the resolution in physical pixels to the resolution in CSS pixels)',
    )
    device_ppi: float = Field(
        ..., alias='device-ppi', description='The device display PPI (pixels per inch)'
    )
    device_price: float = Field(
        ...,
        alias='device-price',
        description='The average device price on release in USD',
    )
    device_release: str = Field(
        ...,
        alias='device-release',
        description='The year when this device model was released',
    )
    device_resolution: str = Field(
        ...,
        alias='device-resolution',
        description='The device display resolution in physical pixels (e.g. 720x1280)',
    )
    device_width_px: float = Field(
        ..., alias='device-width-px', description="The device display width in CSS 'px'"
    )
    is_mobile: bool = Field(
        ...,
        alias='is-mobile',
        description='Is this a mobile device (e.g. a phone or tablet)',
    )
    is_webview: bool = Field(
        ...,
        alias='is-webview',
        description='Is this a WebView / embedded software client',
    )
    name: str = Field(..., description='The client software name')
    os: str = Field(..., description='The full operating system name')
    os_family: str = Field(
        ...,
        alias='os-family',
        description='The operating system family. The major OS families are: Android, Windows, macOS, iOS, Linux',
    )
    os_version: str = Field(
        ..., alias='os-version', description='The operating system full version'
    )
    os_version_major: str = Field(
        ..., alias='os-version-major', description='The operating system major version'
    )
    type: str = Field(
        ...,
        description='The user agent type, possible values are: <br> <ul> <li>desktop</li> <li>phone</li> <li>tablet</li> <li>wearable</li> <li>tv</li> <li>console</li> <li>email</li> <li>library</li> <li>robot</li> <li>unknown</li> </ul>',
    )
    ua: str = Field(..., description='The user agent string')
    version: str = Field(..., description='The client software full version')
    version_major: str = Field(
        ..., alias='version-major', description='The client software major version'
    )


class URLInfoResponse(BaseModel):
    content: str = Field(
        ...,
        description="The actual content this URL responded with. Only set if the 'fetch-content' option was used",
    )
    content_encoding: str = Field(
        ..., alias='content-encoding', description='The encoding format the URL uses'
    )
    content_size: int = Field(
        ..., alias='content-size', description='The size of the URL content in bytes'
    )
    content_type: str = Field(
        ..., alias='content-type', description='The content-type this URL serves'
    )
    http_ok: bool = Field(
        ...,
        alias='http-ok',
        description='True if this URL responded with an HTTP OK (200) status',
    )
    http_redirect: bool = Field(
        ...,
        alias='http-redirect',
        description='True if this URL responded with an HTTP redirect',
    )
    http_status: int = Field(
        ...,
        alias='http-status',
        description='The HTTP status code this URL responded with. An HTTP status of 0 indicates a network level issue',
    )
    http_status_message: int = Field(
        ...,
        alias='http-status-message',
        description='The HTTP status message assoicated with the status code',
    )
    is_error: bool = Field(
        ...,
        alias='is-error',
        description='True if an error occurred while loading the URL. This includes network errors, TLS errors and timeouts',
    )
    is_timeout: bool = Field(
        ...,
        alias='is-timeout',
        description="True if a timeout occurred while loading the URL. You can set the timeout with the request parameter 'timeout'",
    )
    language_code: str = Field(
        ...,
        alias='language-code',
        description='The ISO 2-letter language code of the page. Extracted from either the HTML document or via HTTP headers',
    )
    load_time: float = Field(
        ...,
        alias='load-time',
        description='The time taken to load the URL content in seconds',
    )
    query: Dict[str, str] = Field(
        ..., description='A key-value map of the URL query paramaters'
    )
    real: bool = Field(..., description='Is this URL actually serving real content')
    server_city: str = Field(
        ...,
        alias='server-city',
        description='The servers IP geo-location: full city name (if detectable)',
    )
    server_country: str = Field(
        ...,
        alias='server-country',
        description='The servers IP geo-location: full country name',
    )
    server_country_code: str = Field(
        ...,
        alias='server-country-code',
        description='The servers IP geo-location: ISO 2-letter country code',
    )
    server_hostname: str = Field(
        ..., alias='server-hostname', description='The servers hostname (PTR record)'
    )
    server_ip: str = Field(
        ...,
        alias='server-ip',
        description='The IP address of the server hosting this URL',
    )
    server_name: str = Field(
        ...,
        alias='server-name',
        description='The name of the server software hosting this URL',
    )
    server_region: str = Field(
        ...,
        alias='server-region',
        description='The servers IP geo-location: full region name (if detectable)',
    )
    title: str = Field(..., description='The document title')
    url: str = Field(
        ...,
        description='The fully qualified URL. This may be different to the URL requested if http-redirect is true',
    )
    url_path: str = Field(..., alias='url-path', description='The URL path')
    url_port: int = Field(..., alias='url-port', description='The URL port')
    url_protocol: str = Field(
        ..., alias='url-protocol', description='The URL protocol, usually http or https'
    )
    valid: bool = Field(..., description='Is this a valid well-formed URL')


class VerifySecurityCodeResponse(BaseModel):
    verified: bool = Field(..., description='True if the code is valid')


class BadWordFilterPostRequest(BaseModel):
    catalog: Optional[str] = Field(
        'strict',
        description="Which catalog of bad words to use, we currently maintain two bad word catalogs: <br> <ul> <li>strict - the largest database of bad words which includes profanity, obscenity, sexual, rude, cuss, dirty, swear and objectionable words and phrases. This catalog is suitable for environments of all ages including educational or children's content</li> <li>obscene - like the strict catalog but does not include any mild profanities, idiomatic phrases or words which are considered formal terminology. This catalog is suitable for adult environments where certain types of bad words are considered OK</li> </ul>",
    )
    censor_character: Optional[str] = Field(
        None,
        alias='censor-character',
        description='The character to use to censor out the bad words found',
    )
    content: str = Field(
        ...,
        description='The content to scan. This can be either a URL to load from, a file upload (multipart/form-data) or an HTML content string',
    )


class BrowserBotPostRequest(BaseModel):
    delay: Optional[int] = Field(
        3,
        description='Delay in seconds to wait before capturing any page data, executing selectors or JavaScript',
    )
    exec: Optional[List[str]] = Field(
        '[]',
        description="Execute JavaScript on the website. This parameter accepts JavaScript as either a string containing JavaScript or for sending multiple separate statements a JSON array or POST array can also be used. If a statement returns any value it will be returned in the 'exec-results' response. You can also use the following specially defined user interaction functions: <br> <br> <div> sleep(seconds); Just wait/sleep for the specified number of seconds. <br>click('selector'); Click on the first element matching the given selector. <br>focus('selector'); Focus on the first element matching the given selector. <br>keys('characters'); Send the specified keyboard characters. Use click() or focus() first to send keys to a specific element. <br>enter(); Send the Enter key. <br>tab(); Send the Tab key. <br> </div>",
    )
    ignore_certificate_errors: Optional[bool] = Field(
        False,
        alias='ignore-certificate-errors',
        description='Ignore any TLS/SSL certificate errors and load the page anyway',
    )
    selector: Optional[str] = Field(
        None,
        description='Extract content from the page DOM using this selector. Commonly known as a CSS selector, you can find a good reference <a href="https://www.w3schools.com/cssref/css_selectors.asp">here</a>',
    )
    timeout: Optional[int] = Field(
        30,
        description='Timeout in seconds. Give up if still trying to load the page after this number of seconds',
    )
    url: str = Field(..., description='The URL to load')
    user_agent: Optional[str] = Field(
        None,
        alias='user-agent',
        description='Override the browsers default user-agent string with this one',
    )


class HtmlCleanPostRequest(BaseModel):
    content: str = Field(
        ...,
        description='The HTML content. This can be either a URL to load from, a file upload (multipart/form-data) or an HTML content string',
    )
    output_type: str = Field(
        ...,
        alias='output-type',
        description='The level of sanitization, possible values are: <br><b>plain-text</b>: reduce the content to plain text only (no HTML tags at all) <br><b>simple-text</b>: allow only very basic text formatting tags like b, em, i, strong, u <br><b>basic-html</b>: allow advanced text formatting and hyper links <br><b>basic-html-with-images</b>: same as basic html but also allows image tags <br><b>advanced-html</b>: same as basic html with images but also allows many more common HTML tags like table, ul, dl, pre <br>',
    )


class HtmlRenderPostRequest(BaseModel):
    content: str = Field(
        ...,
        description='The HTML content. This can be either a URL to load from, a file upload (multipart/form-data) or an HTML content string',
    )
    css: Optional[str] = Field(
        None,
        description="Inject custom CSS into the HTML. e.g. 'body { background-color: red;}'",
    )
    delay: Optional[int] = Field(
        0,
        description='Number of seconds to wait before rendering the page (can be useful for pages with animations etc)',
    )
    footer: Optional[str] = Field(
        None,
        description='The footer HTML to insert into each page. The following dynamic tags are supported: {date}, {title}, {url}, {pageNumber}, {totalPages}',
    )
    format: Optional[str] = Field(
        'PDF',
        description='Which format to output, available options are: PDF, PNG, JPG',
    )
    grayscale: Optional[bool] = Field(
        False, description='Render the final document in grayscale'
    )
    header: Optional[str] = Field(
        None,
        description='The header HTML to insert into each page. The following dynamic tags are supported: {date}, {title}, {url}, {pageNumber}, {totalPages}',
    )
    ignore_certificate_errors: Optional[bool] = Field(
        False,
        alias='ignore-certificate-errors',
        description='Ignore any TLS/SSL certificate errors',
    )
    image_height: Optional[int] = Field(
        None,
        alias='image-height',
        description='If rendering to an image format (PNG or JPG) use this image height (in pixels). The default is automatic which dynamically sets the image height based on the content',
    )
    image_width: Optional[int] = Field(
        1024,
        alias='image-width',
        description='If rendering to an image format (PNG or JPG) use this image width (in pixels)',
    )
    landscape: Optional[bool] = Field(
        False, description='Set the document to landscape orientation'
    )
    margin: Optional[float] = Field(0, description='The document margin (in mm)')
    margin_bottom: Optional[float] = Field(
        0, alias='margin-bottom', description='The document bottom margin (in mm)'
    )
    margin_left: Optional[float] = Field(
        0, alias='margin-left', description='The document left margin (in mm)'
    )
    margin_right: Optional[float] = Field(
        0, alias='margin-right', description='The document right margin (in mm)'
    )
    margin_top: Optional[float] = Field(
        0, alias='margin-top', description='The document top margin (in mm)'
    )
    page_height: Optional[float] = Field(
        None,
        alias='page-height',
        description='Set the PDF page height explicitly (in mm)',
    )
    page_size: Optional[str] = Field(
        'A4',
        alias='page-size',
        description='Set the document page size, can be one of: A0 - A9, B0 - B10, Comm10E, DLE or Letter',
    )
    page_width: Optional[float] = Field(
        None,
        alias='page-width',
        description='Set the PDF page width explicitly (in mm)',
    )
    timeout: Optional[int] = Field(
        300,
        description='Timeout in seconds. Give up if still trying to load the HTML content after this number of seconds',
    )
    title: Optional[str] = Field(None, description='The document title')
    zoom: Optional[float] = Field(
        1,
        description='Set the zoom factor when rendering the page (2.0 for double size, 0.5 for half size)',
    )


class ImageResizePostRequest(BaseModel):
    bg_color: Optional[str] = Field(
        'transparent',
        alias='bg-color',
        description="The image background color in hexadecimal notation (e.g. #0000ff). For PNG output the special value of 'transparent' can also be used. For JPG output the default is black (#000000)",
    )
    format: Optional[str] = Field(
        'png', description='The output image format, can be either png or jpg'
    )
    height: Optional[int] = Field(
        None,
        description="The height to resize to (in px). If you don't set this field then the height will be automatic based on the requested width and image aspect ratio",
    )
    image_url: str = Field(
        ...,
        alias='image-url',
        description='The URL or Base64 encoded Data URL for the source image. You can also upload an image file directly using multipart/form-data',
    )
    resize_mode: Optional[str] = Field(
        'scale',
        alias='resize-mode',
        description="The resize mode to use, we support 3 main resizing modes: <ul> <li><b>scale</b><br>Resize to within the width and height specified while preserving aspect ratio. In this mode the width or height will be automatically adjusted to fit the aspect ratio</li> <li><b>pad</b><br>Resize to exactly the width and height specified while preserving aspect ratio and pad any space left over. Any padded space will be filled in with the 'bg-color' value</li> <li><b>crop</b><br>Resize to exactly the width and height specified while preserving aspect ratio and crop any space which fall outside the area. The cropping window is centered on the original image</li> </ul>",
    )
    width: int = Field(..., description='The width to resize to (in px)')


class ImageWatermarkPostRequest(BaseModel):
    bg_color: Optional[str] = Field(
        'transparent',
        alias='bg-color',
        description="The image background color in hexadecimal notation (e.g. #0000ff). For PNG output the special value of 'transparent' can also be used. For JPG output the default is black (#000000)",
    )
    format: Optional[str] = Field(
        'png', description='The output image format, can be either png or jpg'
    )
    height: Optional[int] = Field(
        None, description='If set resize the resulting image to this height (in px)'
    )
    image_url: str = Field(
        ...,
        alias='image-url',
        description='The URL or Base64 encoded Data URL for the source image. You can also upload an image file directly using multipart/form-data',
    )
    opacity: Optional[int] = Field(
        50, description='The opacity of the watermark (0 to 100)'
    )
    position: Optional[str] = Field(
        'center',
        description='The position of the watermark image, possible values are: <br>center, top-left, top-center, top-right, bottom-left, bottom-center, bottom-right',
    )
    resize_mode: Optional[str] = Field(
        'scale',
        alias='resize-mode',
        description="The resize mode to use, we support 3 main resizing modes: <ul> <li><b>scale</b><br>Resize to within the width and height specified while preserving aspect ratio. In this mode the width or height will be automatically adjusted to fit the aspect ratio</li> <li><b>pad</b><br>Resize to exactly the width and height specified while preserving aspect ratio and pad any space left over. Any padded space will be filled in with the 'bg-color' value</li> <li><b>crop</b><br>Resize to exactly the width and height specified while preserving aspect ratio and crop any space which fall outside the area. The cropping window is centered on the original image</li> </ul>",
    )
    watermark_url: str = Field(
        ...,
        alias='watermark-url',
        description='The URL or Base64 encoded Data URL for the watermark image. You can also upload an image file directly using multipart/form-data',
    )
    width: Optional[int] = Field(
        None, description='If set resize the resulting image to this width (in px)'
    )


class PhonePlaybackPostRequest(BaseModel):
    audio_url: str = Field(
        ...,
        alias='audio-url',
        description='A URL to a valid audio file. Accepted audio formats are: <ul> <li>MP3</li> <li>WAV</li> <li>OGG</li> </ul>You can use the following MP3 URL for testing: <br>https://www.neutrinoapi.com/test-files/test1.mp3',
    )
    limit: Optional[int] = Field(
        3,
        description='Limit the total number of calls allowed to the supplied phone number, if the limit is reached within the TTL then error code 14 will be returned',
    )
    limit_ttl: Optional[int] = Field(
        1,
        alias='limit-ttl',
        description="Set the TTL in number of days that the 'limit' option will remember a phone number (the default is 1 day and the maximum is 365 days)",
    )
    number: str = Field(
        ...,
        description='The phone number to call. Must be in valid international format',
    )


class PhoneVerifyPostRequest(BaseModel):
    code_length: Optional[int] = Field(
        6,
        alias='code-length',
        description='The number of digits to use in the security code (between 4 and 12)',
    )
    country_code: Optional[str] = Field(
        None,
        alias='country-code',
        description='ISO 2-letter country code, assume numbers are based in this country. <br>If not set numbers are assumed to be in international format (with or without the leading + sign)',
    )
    language_code: Optional[str] = Field(
        'en',
        alias='language-code',
        description='The language to playback the verification code in, available languages are: <ul> <li>de - German</li> <li>en - English</li> <li>es - Spanish</li> <li>fr - French</li> <li>it - Italian</li> <li>pt - Portuguese</li> <li>ru - Russian</li> </ul>',
    )
    limit: Optional[int] = Field(
        3,
        description='Limit the total number of calls allowed to the supplied phone number, if the limit is reached within the TTL then error code 14 will be returned',
    )
    limit_ttl: Optional[int] = Field(
        1,
        alias='limit-ttl',
        description="Set the TTL in number of days that the 'limit' option will remember a phone number (the default is 1 day and the maximum is 365 days)",
    )
    number: str = Field(
        ..., description='The phone number to send the verification code to'
    )
    playback_delay: Optional[int] = Field(
        800,
        alias='playback-delay',
        description='The delay in milliseconds between the playback of each security code',
    )
    security_code: Optional[int] = Field(
        None,
        alias='security-code',
        description='Pass in your own security code. This is useful if you have implemented TOTP or similar 2FA methods. If not set then we will generate a secure random code',
    )


class QrCodePostRequest(BaseModel):
    bg_color: Optional[str] = Field(
        '#ffffff', alias='bg-color', description='The QR code background color'
    )
    content: str = Field(
        ...,
        description='The content to encode into the QR code (e.g. a URL or a phone number)',
    )
    fg_color: Optional[str] = Field(
        '#000000', alias='fg-color', description='The QR code foreground color'
    )
    height: Optional[int] = Field(256, description='The height of the QR code (in px)')
    width: Optional[int] = Field(256, description='The width of the QR code (in px)')


class SmsVerifyPostRequest(BaseModel):
    code_length: Optional[int] = Field(
        5,
        alias='code-length',
        description='The number of digits to use in the security code (must be between 4 and 12)',
    )
    country_code: Optional[str] = Field(
        None,
        alias='country-code',
        description='ISO 2-letter country code, assume numbers are based in this country. <br>If not set numbers are assumed to be in international format (with or without the leading + sign)',
    )
    language_code: Optional[str] = Field(
        'en',
        alias='language-code',
        description='The language to send the verification code in, available languages are: <ul> <li>de - German</li> <li>en - English</li> <li>es - Spanish</li> <li>fr - French</li> <li>it - Italian</li> <li>pt - Portuguese</li> <li>ru - Russian</li> </ul>',
    )
    limit: Optional[int] = Field(
        10,
        description='Limit the total number of SMS allowed to the supplied phone number, if the limit is reached within the TTL then error code 14 will be returned',
    )
    limit_ttl: Optional[int] = Field(
        1,
        alias='limit-ttl',
        description="Set the TTL in number of days that the 'limit' option will remember a phone number (the default is 1 day and the maximum is 365 days)",
    )
    number: str = Field(
        ..., description='The phone number to send a verification code to'
    )
    security_code: Optional[int] = Field(
        None,
        alias='security-code',
        description='Pass in your own security code. This is useful if you have implemented TOTP or similar 2FA methods. If not set then we will generate a secure random code',
    )


class GeocodeReverseResponse(BaseModel):
    address: str = Field(
        ..., description='The complete address using comma-separated values'
    )
    address_components: Dict[str, str] = Field(
        ...,
        alias='address-components',
        description='The components which make up the address such as road, city, state, etc',
    )
    city: str = Field(..., description='The city of the location')
    country: str = Field(..., description='The country of the location')
    country_code: str = Field(
        ...,
        alias='country-code',
        description='The ISO 2-letter country code of the location',
    )
    country_code3: str = Field(
        ...,
        alias='country-code3',
        description='The ISO 3-letter country code of the location',
    )
    currency_code: str = Field(
        ...,
        alias='currency-code',
        description='ISO 4217 currency code associated with the country',
    )
    found: bool = Field(
        ..., description='True if these coordinates map to a real location'
    )
    latitude: float = Field(..., description='The location latitude')
    location_tags: List[str] = Field(
        ...,
        alias='location-tags',
        description='Array of strings containing any location tags associated with the address. Tags are additional pieces of metadata about a specific location, there are thousands of different tags. Some examples of tags: shop, office, cafe, bank, pub',
    )
    location_type: str = Field(
        ...,
        alias='location-type',
        description='The detected location type ordered roughly from most to least precise, possible values are: <br> <ul> <li>address - indicates a precise street address</li> <li>street - accurate to the street level but may not point to the exact location of the house/building number</li> <li>city - accurate to the city level, this includes villages, towns, suburbs, etc</li> <li>postal-code - indicates a postal code area (no house or street information present)</li> <li>railway - location is part of a rail network such as a station or railway track</li> <li>natural - indicates a natural feature, for example a mountain peak or a waterway</li> <li>island - location is an island or archipelago</li> <li>administrative - indicates an administrative boundary such as a country, state or province</li> </ul>',
    )
    longitude: float = Field(..., description='The location longitude')
    postal_address: str = Field(
        ...,
        alias='postal-address',
        description='The formatted address using local standards suitable for printing on an envelope',
    )
    postal_code: str = Field(
        ..., alias='postal-code', description='The postal code for the location'
    )
    region_code: str = Field(
        ...,
        alias='region-code',
        description='The ISO 3166-2 region code for the location',
    )
    state: str = Field(..., description='The state of the location')
    timezone: Dict[str, Timezone] = Field(
        ..., description='Map containing timezone details for the location'
    )


class IPInfoResponse(BaseModel):
    city: str = Field(..., description='Name of the city (if detectable)')
    continent_code: str = Field(
        ..., alias='continent-code', description='ISO 2-letter continent code'
    )
    country: str = Field(..., description='Full country name')
    country_code: str = Field(
        ..., alias='country-code', description='ISO 2-letter country code'
    )
    country_code3: str = Field(
        ..., alias='country-code3', description='ISO 3-letter country code'
    )
    currency_code: str = Field(
        ...,
        alias='currency-code',
        description='ISO 4217 currency code associated with the country',
    )
    host_domain: str = Field(
        ...,
        alias='host-domain',
        description='The IPs host domain (only set if reverse-lookup has been used)',
    )
    hostname: str = Field(
        ...,
        description='The IPs full hostname (only set if reverse-lookup has been used)',
    )
    ip: str = Field(..., description='The IP address')
    is_bogon: bool = Field(
        ...,
        alias='is-bogon',
        description='True if this is a bogon IP address such as a private network, local network or reserved address',
    )
    is_v4_mapped: bool = Field(
        ...,
        alias='is-v4-mapped',
        description='True if this is a <a href="https://en.wikipedia.org/wiki/IPv6#IPv4-mapped_IPv6_addresses">IPv4 mapped IPv6 address</a>',
    )
    is_v6: bool = Field(
        ..., alias='is-v6', description='True if this is a IPv6 address. False if IPv4'
    )
    latitude: float = Field(..., description='Location latitude')
    longitude: float = Field(..., description='Location longitude')
    region: str = Field(..., description='Name of the region (if detectable)')
    region_code: str = Field(
        ..., alias='region-code', description='ISO 3166-2 region code (if detectable)'
    )
    timezone: Dict[str, Timezone] = Field(
        ..., description='Map containing timezone details for the location'
    )
    valid: bool = Field(..., description='True if this is a valid IPv4 or IPv6 address')


class Location(BaseModel):
    address: str = Field(
        ..., description='The complete address using comma-separated values'
    )
    address_components: Dict[str, str] = Field(
        ...,
        alias='address-components',
        description='The components which make up the address such as road, city, state, etc',
    )
    city: str = Field(..., description='The city of the location')
    country: str = Field(..., description='The country of the location')
    country_code: str = Field(
        ...,
        alias='country-code',
        description='The ISO 2-letter country code of the location',
    )
    country_code3: str = Field(
        ...,
        alias='country-code3',
        description='The ISO 3-letter country code of the location',
    )
    currency_code: str = Field(
        ...,
        alias='currency-code',
        description='ISO 4217 currency code associated with the country',
    )
    latitude: float = Field(..., description='The location latitude')
    location_tags: List[str] = Field(
        ...,
        alias='location-tags',
        description='Array of strings containing any location tags associated with the address. Tags are additional pieces of metadata about a specific location, there are thousands of different tags. Some examples of tags: shop, office, cafe, bank, pub',
    )
    location_type: str = Field(
        ...,
        alias='location-type',
        description='The detected location type ordered roughly from most to least precise, possible values are: <br> <ul> <li>address - indicates a precise street address</li> <li>street - accurate to the street level but may not point to the exact location of the house/building number</li> <li>city - accurate to the city level, this includes villages, towns, suburbs, etc</li> <li>postal-code - indicates a postal code area (no house or street information present)</li> <li>railway - location is part of a rail network such as a station or railway track</li> <li>natural - indicates a natural feature, for example a mountain peak or a waterway</li> <li>island - location is an island or archipelago</li> <li>administrative - indicates an administrative boundary such as a country, state or province</li> </ul>',
    )
    longitude: float = Field(..., description='The location longitude')
    postal_address: str = Field(
        ...,
        alias='postal-address',
        description='The formatted address using local standards suitable for printing on an envelope',
    )
    postal_code: str = Field(
        ..., alias='postal-code', description='The postal code for the location'
    )
    region_code: str = Field(
        ...,
        alias='region-code',
        description='The ISO 3166-2 region code for the location',
    )
    state: str = Field(..., description='The state of the location')
    timezone: Dict[str, Timezone] = Field(
        ..., description='Map containing timezone details for the location'
    )


class GeocodeAddressResponse(BaseModel):
    found: int = Field(
        ..., description='The number of possible matching locations found'
    )
    locations: List[Location] = Field(
        ..., description='Array of matching location objects'
    )
